import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import success from "../../successful.json";
import Lottie from "lottie-react";
import { useLottie } from "lottie-react";
import { gsap } from "gsap";
import React, { useRef, useEffect, useState } from "react";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import { useRouter } from "next/router";
import Link from "next/link";

const font = Inter({ subsets: ["latin"] });

export default function Home() {
	const { t: translate } = useTranslation("home");
	const { locale, locales } = useRouter();
	const elementRef = useRef(null);

	useEffect(() => {
		const element = elementRef.current;

		// 	gsap.fromTo(
		// 		element,
		// 		{ opacity: 0, y: 100 },
		// 		{
		// 			opacity: 1,
		// 			y: 0,
		// 			duration: 1,
		// 			ease: "power2.out",
		// 			scrollTrigger: {
		// 				trigger: element,
		// 				start: "top 80%",
		// 				end: "bottom 20%",
		// 				scrub: true,
		// 			},
		// 		}
		// 	);
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<section className="h-[100dvh] flex flex-col justify-center">
				<div className="w-[90%] lg:w-[80%] mx-auto space-y-[2.2rem]">
					<div className="space-y-1">
						<h1 className={`${font.className} uppercase text-[2.5rem] font-extrabold leading-[1.25]`}>
							{translate("heroHeading")}{" "}
						</h1>
						<p className="font-medium text-[1.2rem] leading-[1.5]">{translate("heroSubtitle")}</p>
					</div>
					<div className="flex items-center gap-4 font-medium uppercase text-sm">
						<Link className="dark:bg-[#9393F9] text-text bg-red-600 px-5 py-3 rounded-3xl" href="/#contact">{translate("heroCta1")}</Link>
						<Link className="dark:bg-[#9393F9] text-text bg-red-600 px-5 py-3 rounded-3xl" href="/#value">{translate("heroCta2")}</Link>
					</div>
				</div>
			</section>
			{/* <h1 className="">{locale}</h1>
			<section className="">
				<h1 className="">{translate("h1")} </h1>
			</section>
			<Link href="/" locale={locale} key={locale}>
				refresh
			</Link>
			{locales.map((locale) => (
				<div className="flex gap-4" key={locale}>
					<Link href="/" locale={locale}>
						{locale}
					</Link>
				</div>
			))} */}
		</>
	);
}

export async function getStaticProps({ locale, defaultLocale }) {
	// console.log(locale);
	return {
		props: {
			...(await serverSideTranslations(locale ?? defaultLocale, ["common", "home", "header", "footer"])),
		},
	};
}
