import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import success from "../../successful.json";
import Lottie from "lottie-react";
import { useLottie } from "lottie-react";
import { gsap } from "gsap";
import React, { useRef, useEffect, useState } from "react";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import { useRouter } from "next/router";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
	
	const elementRef = useRef(null);

	useEffect(() => {
		const element = elementRef.current;

		gsap.fromTo(
			element,
			{ opacity: 0, y: 100 },
			{
				opacity: 1,
				y: 0,
				duration: 1,
				ease: "power2.out",
				scrollTrigger: {
					trigger: element,
					start: "top 80%",
					end: "bottom 20%",
					scrub: true,
				},
			}
		);
	}, []);
	const { locale, locales } = useRouter();

	const { t: translate } = useTranslation("home");
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<section className="">
				<h1 className=""></h1>
				<p className=""></p>
			</section>
			{/* <h1 className="">{locale}</h1>
			<section className="">
				<h1 className="">{translate("h1")} </h1>
			</section>
			<Link href="/" locale={locale} key={locale}>
				refresh
			</Link>
			{locales.map((locale) => (
				<div className="flex gap-4" key={locale}>
					<Link href="/" locale={locale}>
						{locale}
					</Link>
				</div>
			))} */}
		</>
	);
}

export async function getStaticProps({ locale, defaultLocale }) {
	// console.log(locale);
	return {
		props: {
			...(await serverSideTranslations(locale ?? defaultLocale, ["common", "home", "header", "footer"])),
		},
	};
}
